export const QUIZ_LABELS = {
  pt: {
    badge: "QUIZ INTERATIVO",
    triviaBadge: "TRIVIA",
    personalityBadge: "PERSONALIDADE",
    questionsLabel: "perguntas",
    minLabel: "min",
    startQuiz: "COMEÇAR QUIZ",
    questionOf: "PERGUNTA",
    of: "DE",
    completed: "CONCLUÍDO",
    previous: "VOLTAR",
    next: "PRÓXIMO",
    finish: "VER RESULTADO",
    correct: "CORRETO",
    incorrect: "INCORRETO",
    explanation: "EXPLICAÇÃO",
    source: "Fonte",
    resultBadge: "SEU RESULTADO",
    scoreBadge: "PONTUAÇÃO FINAL",
    traits: "CARACTERÍSTICAS",
    shareTitle: "COMPARTILHAR RESULTADO",
    shareWhatsApp: "WhatsApp",
    shareTwitter: "X / Twitter",
    shareCopy: "Copiar Link",
    shareNative: "Compartilhar",
    copied: "Copiado!",
    downloadCard: "Baixar Card (Story)",
    downloading: "Gerando...",
    retake: "JOGAR NOVAMENTE",
    moreQuizzes: "EXPLORAR OUTROS QUIZZES",
    hits: "acertos",
    brandFooter: "toolnotch.com • Quizzes & Ferramentas Gratuitas",
  },
  en: {
    badge: "INTERACTIVE QUIZ",
    triviaBadge: "TRIVIA",
    personalityBadge: "PERSONALITY",
    questionsLabel: "questions",
    minLabel: "min",
    startQuiz: "START QUIZ",
    questionOf: "QUESTION",
    of: "OF",
    completed: "COMPLETED",
    previous: "BACK",
    next: "NEXT",
    finish: "SEE RESULT",
    correct: "CORRECT",
    incorrect: "INCORRECT",
    explanation: "EXPLANATION",
    source: "Source",
    resultBadge: "YOUR RESULT",
    scoreBadge: "FINAL SCORE",
    traits: "TRAITS",
    shareTitle: "SHARE RESULT",
    shareWhatsApp: "WhatsApp",
    shareTwitter: "X / Twitter",
    shareCopy: "Copy Link",
    shareNative: "Share",
    copied: "Copied!",
    downloadCard: "Download Card (Story)",
    downloading: "Generating...",
    retake: "RETAKE QUIZ",
    moreQuizzes: "EXPLORE MORE QUIZZES",
    hits: "correct",
    brandFooter: "toolnotch.com • Free Quizzes & Tools",
  },
  es: {
    badge: "QUIZ INTERACTIVO",
    triviaBadge: "TRIVIA",
    personalityBadge: "PERSONALIDAD",
    questionsLabel: "preguntas",
    minLabel: "min",
    startQuiz: "COMENZAR QUIZ",
    questionOf: "PREGUNTA",
    of: "DE",
    completed: "COMPLETADO",
    previous: "VOLVER",
    next: "SIGUIENTE",
    finish: "VER RESULTADO",
    correct: "CORRECTO",
    incorrect: "INCORRECTO",
    explanation: "EXPLICACIÓN",
    source: "Fuente",
    resultBadge: "TU RESULTADO",
    scoreBadge: "PUNTUACIÓN FINAL",
    traits: "CARACTERÍSTICAS",
    shareTitle: "COMPARTIR RESULTADO",
    shareWhatsApp: "WhatsApp",
    shareTwitter: "X / Twitter",
    shareCopy: "Copiar Enlace",
    shareNative: "Compartir",
    copied: "¡Copiado!",
    downloadCard: "Descargar Card (Story)",
    downloading: "Generando...",
    retake: "REPETIR QUIZ",
    moreQuizzes: "EXPLORAR MÁS QUIZZES",
    hits: "aciertos",
    brandFooter: "toolnotch.com • Quizzes & Herramientas Gratuitas",
  },
} as const;

export type QuizLabels = {
  [K in keyof (typeof QUIZ_LABELS)["pt"]]: string;
};

export function getQuizLabels(locale?: string): QuizLabels {
  const currentLocale = locale === "pt" || locale === "es" ? locale : "en";
  return QUIZ_LABELS[currentLocale] || QUIZ_LABELS.en;
}
